# Generated by Django 6.0 on 2025-12-31 16:30

import django.db.models.deletion
from django.db import migrations, models


def ensure_task_path_guard(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return

    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            """
            CREATE OR REPLACE FUNCTION reproq_task_path_from_spec()
            RETURNS trigger AS $$
            BEGIN
                IF NEW.task_path IS NULL OR NEW.task_path = '' THEN
                    NEW.task_path := NEW.spec_json->>'task_path';
                END IF;
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;
            """
        )
        cursor.execute("DROP TRIGGER IF EXISTS trg_task_runs_task_path ON task_runs;")
        cursor.execute(
            """
            CREATE TRIGGER trg_task_runs_task_path
            BEFORE INSERT OR UPDATE OF spec_json, task_path ON task_runs
            FOR EACH ROW
            EXECUTE FUNCTION reproq_task_path_from_spec();
            """
        )
        cursor.execute(
            """
            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1 FROM pg_constraint WHERE conname = 'task_runs_task_path_not_empty'
                ) THEN
                    ALTER TABLE task_runs
                    ADD CONSTRAINT task_runs_task_path_not_empty CHECK (task_path IS NOT NULL AND task_path <> '');
                END IF;
            END $$;
            """
        )
        cursor.execute(
            """
            CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_task_runs_task_path
            ON task_runs (task_path);
            """
        )
        cursor.execute(
            """
            CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_task_runs_claim_due
            ON task_runs (queue_name, COALESCE(run_after, '-infinity'::timestamptz), priority DESC, enqueued_at ASC)
            WHERE status = 'READY';
            """
        )


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    replaces = [
        ("reproq_django", "0001_initial"),
        ("reproq_django", "0002_taskrun_indexes"),
        (
            "reproq_django",
            "0003_rename_idx_task_runs_status_task_runs_status_26197d_idx_and_more",
        ),
    ]

    atomic = False

    operations = [
        migrations.CreateModel(
            name="PeriodicTask",
            fields=[
                ("name", models.TextField(primary_key=True, serialize=False)),
                ("cron_expr", models.TextField()),
                ("task_path", models.TextField()),
                ("payload_json", models.JSONField(blank=True, default=dict)),
                ("queue_name", models.TextField(default="default")),
                ("priority", models.IntegerField(default=0)),
                ("max_attempts", models.IntegerField(default=3)),
                ("concurrency_key", models.TextField(blank=True, null=True)),
                ("concurrency_limit", models.IntegerField(default=0)),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
                ("next_run_at", models.DateTimeField()),
                ("enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Periodic Task",
                "verbose_name_plural": "Periodic Tasks",
                "db_table": "periodic_tasks",
            },
        ),
        migrations.CreateModel(
            name="QueueControl",
            fields=[
                ("queue_name", models.TextField(primary_key=True, serialize=False)),
                ("paused", models.BooleanField(default=False)),
                ("paused_at", models.DateTimeField(blank=True, null=True)),
                ("reason", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Queue Control",
                "verbose_name_plural": "Queue Controls",
                "db_table": "reproq_queue_controls",
            },
        ),
        migrations.CreateModel(
            name="Worker",
            fields=[
                ("worker_id", models.TextField(primary_key=True, serialize=False)),
                ("hostname", models.TextField()),
                ("concurrency", models.IntegerField()),
                ("queues", models.JSONField(default=list)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("last_seen_at", models.DateTimeField(auto_now=True)),
                ("version", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Worker",
                "verbose_name_plural": "Workers",
                "db_table": "reproq_workers",
            },
        ),
        migrations.CreateModel(
            name="TaskRun",
            fields=[
                ("result_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("backend_alias", models.TextField(default="default")),
                ("queue_name", models.TextField(default="default")),
                ("priority", models.IntegerField(default=0)),
                ("run_after", models.DateTimeField(blank=True, null=True)),
                ("spec_json", models.JSONField()),
                ("spec_hash", models.CharField(max_length=64)),
                ("task_path", models.TextField(blank=True, null=True)),
                ("status", models.TextField(default="READY")),
                ("enqueued_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("last_attempted_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("attempts", models.IntegerField(default=0)),
                ("max_attempts", models.IntegerField(default=3)),
                ("timeout_seconds", models.IntegerField(default=900)),
                ("lock_key", models.TextField(blank=True, null=True)),
                ("concurrency_key", models.TextField(blank=True, null=True)),
                ("concurrency_limit", models.IntegerField(default=0)),
                ("workflow_id", models.UUIDField(blank=True, null=True)),
                ("wait_count", models.IntegerField(default=0)),
                ("worker_ids", models.JSONField(blank=True, default=list)),
                ("return_json", models.JSONField(blank=True, null=True)),
                ("errors_json", models.JSONField(blank=True, default=list)),
                ("metadata_json", models.JSONField(blank=True, default=dict)),
                ("last_error", models.TextField(blank=True, null=True)),
                ("failed_at", models.DateTimeField(blank=True, null=True)),
                ("leased_until", models.DateTimeField(blank=True, null=True)),
                ("leased_by", models.TextField(blank=True, null=True)),
                ("logs_uri", models.TextField(blank=True, null=True)),
                ("artifacts_uri", models.TextField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("cancel_requested", models.BooleanField(default=False)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="reproq_django.taskrun",
                    ),
                ),
            ],
            options={
                "verbose_name": "Task Run",
                "verbose_name_plural": "Task Runs",
                "db_table": "task_runs",
                "permissions": [("can_replay_taskrun", "Can replay task run")],
                "indexes": [
                    models.Index(fields=["status"], name="task_runs_status_26197d_idx"),
                    models.Index(
                        fields=["queue_name", "status"],
                        name="task_runs_queue_n_50e8d6_idx",
                    ),
                    models.Index(
                        fields=["concurrency_key", "status"],
                        name="task_runs_concurrency_key_status_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="WorkflowRun",
            fields=[
                ("workflow_id", models.UUIDField(primary_key=True, serialize=False)),
                ("expected_count", models.IntegerField()),
                ("success_count", models.IntegerField(default=0)),
                ("failure_count", models.IntegerField(default=0)),
                ("callback_result_id", models.BigIntegerField(blank=True, null=True)),
                ("status", models.TextField(default="RUNNING")),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
            ],
            options={
                "verbose_name": "Workflow Run",
                "verbose_name_plural": "Workflow Runs",
                "db_table": "workflow_runs",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="RateLimit",
            fields=[
                ("key", models.TextField(primary_key=True, serialize=False)),
                ("tokens_per_second", models.FloatField()),
                ("burst_size", models.IntegerField()),
                ("current_tokens", models.FloatField()),
                ("last_refilled_at", models.DateTimeField()),
            ],
            options={
                "verbose_name": "Rate Limit",
                "verbose_name_plural": "Rate Limits",
                "db_table": "rate_limits",
                "managed": False,
            },
        ),
        migrations.RunPython(ensure_task_path_guard, migrations.RunPython.noop),
    ]
