# Generated by Django 6.0 on 2025-12-29 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PeriodicTask",
            fields=[
                ("name", models.TextField(primary_key=True, serialize=False)),
                ("cron_expr", models.TextField()),
                ("task_path", models.TextField()),
                ("payload_json", models.JSONField(blank=True, default=dict)),
                ("queue_name", models.TextField(default="default")),
                ("priority", models.IntegerField(default=0)),
                ("max_attempts", models.IntegerField(default=3)),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
                ("next_run_at", models.DateTimeField()),
                ("enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Periodic Task",
                "verbose_name_plural": "Periodic Tasks",
                "db_table": "periodic_tasks",
            },
        ),
        migrations.CreateModel(
            name="Worker",
            fields=[
                ("worker_id", models.TextField(primary_key=True, serialize=False)),
                ("hostname", models.TextField()),
                ("concurrency", models.IntegerField()),
                ("queues", models.JSONField(default=list)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("last_seen_at", models.DateTimeField(auto_now=True)),
                ("version", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Worker",
                "verbose_name_plural": "Workers",
                "db_table": "reproq_workers",
            },
        ),
        migrations.CreateModel(
            name="TaskRun",
            fields=[
                ("result_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("backend_alias", models.TextField(default="default")),
                ("queue_name", models.TextField(default="default")),
                ("priority", models.IntegerField(default=0)),
                ("run_after", models.DateTimeField(blank=True, null=True)),
                ("spec_json", models.JSONField()),
                ("spec_hash", models.CharField(max_length=64)),
                ("status", models.TextField(default="READY")),
                ("enqueued_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("last_attempted_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("attempts", models.IntegerField(default=0)),
                ("max_attempts", models.IntegerField(default=3)),
                ("timeout_seconds", models.IntegerField(default=900)),
                ("lock_key", models.TextField(blank=True, null=True)),
                ("workflow_id", models.UUIDField(blank=True, null=True)),
                ("wait_count", models.IntegerField(default=0)),
                ("worker_ids", models.JSONField(blank=True, default=list)),
                ("return_json", models.JSONField(blank=True, null=True)),
                ("errors_json", models.JSONField(blank=True, default=list)),
                ("leased_until", models.DateTimeField(blank=True, null=True)),
                ("leased_by", models.TextField(blank=True, null=True)),
                ("logs_uri", models.TextField(blank=True, null=True)),
                ("artifacts_uri", models.TextField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("cancel_requested", models.BooleanField(default=False)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="reproq_django.taskrun",
                    ),
                ),
            ],
            options={
                "verbose_name": "Task Run",
                "verbose_name_plural": "Task Runs",
                "db_table": "task_runs",
                "permissions": [("can_replay_taskrun", "Can replay task run")],
            },
        ),
    ]
