# Generated by Django 6.0 on 2025-12-31 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reproq_django", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="taskrun",
            index=models.Index(fields=["status"], name="idx_task_runs_status"),
        ),
        migrations.AddIndex(
            model_name="taskrun",
            index=models.Index(fields=["queue_name", "status"], name="idx_task_runs_queue_status"),
        ),
    ]
