# Generated by Django 6.0 on 2025-12-29 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reproq_django", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskrun",
            name="last_error",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="taskrun",
            name="failed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
